# Generated by Django 5.0 on 2023-12-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=100, verbose_name='Description')),
                ('capture_date', models.DateField(verbose_name='Capture date')),
                ('photo', models.ImageField(default=None, null=True, upload_to='', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=100, verbose_name='Description')),
                ('main_photo', models.ImageField(default=None, upload_to='', verbose_name='Main picture')),
                ('photo_2', models.ImageField(default=None, null=True, upload_to='', verbose_name='Photo 2')),
                ('photo_3', models.ImageField(default=None, null=True, upload_to='', verbose_name='Photo 3')),
                ('start_date', models.DateField(verbose_name='Started date')),
                ('end_date', models.DateField(default=None, null=True, verbose_name='End date')),
                ('project_link', models.CharField(default=None, max_length=65, null=True, verbose_name='Project Link')),
            ],
        ),
    ]
