# Generated by Django 5.0 on 2023-12-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.CharField(default='', max_length=40, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=600, verbose_name='Description'),
        ),
    ]
